#!/bin/bash
#Purpose: AWS-CLI
#OS: Ubuntu-18-LTS

#https://linuxhint.com/install_aws_cli_ubuntu/
#https://docs.aws.amazon.com/cli/latest/userguide/install-linux.html#install-linux-path

sudo apt update -y

sudo apt-get install python3-pip -y 

sudo pip3 install awscli --upgrade --user

#This command inserts the path, ~/.local/bin in this example, at the front of the existing PATH variable
export PATH=~/.local/bin:$PATH

#Reload the profile into your current session to put those changes into effect.
source ~/.bash_profile

awscli --version

#END
