#!/bin/bash
#Purpose: Installation of ECS-AGENT, ec2 instance joins the ECS Cluster
# Note on the SG (security group) open the http port 80
mkdir -p /etc/ecs
touch /etc/ecs/ecs.config
echo ECS_CLUSTER=ecs-demo > /etc/ecs/ecs.config




# Update the packages

sudo yum install -y docker
sudo service docker start
sudo usermod -aG docker $USER

sudo yum install -y ecs-init
sudo stop ecs   2>&1   > /dev/null
sudo start ecs

#Note: ecs agent will not start unless docker daemon will not start & running


# To check the logs
# cd /var/log/ecs/
# tail -f ecs*

# ECS_endpoints

# ecs agent listen on port 51678

sudo yum install -y jq

#Note ECS Cluster default port is 51678

curl http://localhost:51678/v1/metadata | jq

# Check the tasks metadata

curl http://localhost:51678/v1/tasks | jq



##End




# Creating an SSH Keypair

#OSX / Linux: Create a keypair

1. aws ec2 create-key-pair --key-name Linux-Academy --query 'KeyMaterial' \
--output text > ~/.ssh/Linux-Academy.pem

2. chmod 400 ~/.ssh/Linux-Academy.pem

# Verify the keypair has been created

3. aws ec2 describe-key-pairs --key-name Linux-Academy

# (Optionally)Delete the keypair

4. aws ec2 delete-key-pair --key-name Linux-Academy

# List IAM users

5. aws iam list-users


############################################# ECS Command Line #############################################################################

# Deep Dive with Amazon ECS
# Clusters
# Create a cluster

aws ecs create-cluster --cluster-name deepdive

#List all clusters

aws ecs list-clusters

# A deeper look into the cluster's state

aws ecs describe-clusters --clusters deepdive

# (Optionally)Delete the cluster

aws ecs delete-cluster --cluster deepdive

# ● Do not delete it now unless you're experimenting on your own
